### ISSUE TITLE
EOL date moved to 19 March 2024

### ISSUE THREAD

**Issue by wjt** [flathub/com.authy.Authy#16]
I received this email today:

> Starting March 19, 2024, Twilio Desktop Authy apps will reach their end of life (EOL). Beyond this date, you can access most of the desktop features and functionality in the mobile Authy apps.
>
> You may have previously seen an August 19, 2024, end of life (EOL) date for Twilio Desktop Authy apps. **This date has been moved up to March 19, 2024.**

https://help.twilio.com/articles/22771146070299-End-user-guide-End-of-Life-EOL-for-Twilio-Authy-Desktop-app

**Comment by prodrigestivill** [comment]
Thanks for the report,

merging the updated metadata at PR #17 so that it appears in flathub store with the new date.
