### ISSUE TITLE
Remove from flathub as the app had reached EoL

### ISSUE THREAD

**Issue by prodrigestivill** [flathub/com.authy.Authy#18]
This app had reached their [End-of-Life on March 19, 2024](https://help.twilio.com/articles/22771146070299-User-guide-End-of-Life-EOL-for-Twilio-Authy-Desktop-app).
It has already been added a warning in the description in 13c7f01cd909af165e88179bfbe8ca1bd4287f82.

And I was waiting to see what would they do in the original snap store, and it seams today they removed if from [there](https://snapcraft.io/authy).

I think it would be best to remove it from flathub too.

Thanks.

cc: @barthalion @hfiguiere as reviewers of https://github.com/flathub/flathub/pull/3729

**Comment by hfiguiere** [comment]
it's rude to assign work to volunteers.

**Comment by prodrigestivill** [comment]
Merge and publish [failed](https://buildbot.flathub.org/#/builders/6/builds/108751) caused by a flathub API issue.

It is a problem affecting other app deployments, the conversation is being done at [#flathub:matrix.org](https://matrix.to/#/#flathub:matrix.org).

**Comment by hfiguiere** [comment]
it was rebuilt.
